name: SecureAuth
version: '${version}'
main: org.alex_melan.secureAuth.SecureAuthPlugin
api-version: '1.20'
authors: [ Alex Melan ]
website: https://github.com/AlexMelanFromRingo
description: Secure authentication plugin for offline mode servers

softdepend: [Vault]

commands:
  login:
    description: Login to your account
    usage: /login <password>
    aliases: [l, auth, log]

  register:
    description: Register a new account
    usage: /register <password> <confirm_password>
    aliases: [reg, signup]

  logout:
    description: Logout from your account
    usage: /logout
    aliases: [exit, quit]

  secureauth:
    description: SecureAuth admin commands
    usage: /secureauth <subcommand>
    aliases: [sauth, sa]
    permission: secureauth.admin

permissions:
  secureauth.admin:
    description: Admin permissions for SecureAuth
    default: op
    children:
      - secureauth.reload
      - secureauth.forcelogout
      - secureauth.sessions
      - secureauth.cleanup

  secureauth.reload:
    description: Reload plugin configuration
    default: op

  secureauth.forcelogout:
    description: Force logout players
    default: op

  secureauth.sessions:
    description: View active sessions
    default: op

  secureauth.cleanup:
    description: Clean expired sessions
    default: op

  secureauth.bypass:
    description: Bypass authentication (for console commands)
    default: false