name: SecureAuth
version: '1.0-SNAPSHOT'
main: org.alex_melan.secureAuth.SecureAuthPlugin
api-version: '1.20'
authors: [ Alex Melan ]
website: https://github.com/AlexMelanFromRingo
description: Secure authentication plugin for offline mode servers

softdepend: [Vault]

commands:
  login:
    description: Login to your account
    usage: /login <password>
    aliases: [l, auth, log]

  register:
    description: Register a new account
    usage: /register <password> <confirm_password>
    aliases: [reg, signup]

permissions:
  secureauth.admin:
    description: Admin permissions for SecureAuth
    default: op

  secureauth.bypass:
    description: Bypass authentication (for console commands)
    default: false